/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package starnet;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.format.DateTimeFormatter;  
import java.time.LocalDateTime; 
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author junnu
 */
public class StatementEntry extends javax.swing.JFrame {

    /**
     * Creates new form StatementEntry
     */
    Connection conn=null;
    String def_val[]=new String[14];
    public StatementEntry() {
        initComponents();
        jButton1.requestFocusInWindow();
        this.initialvalues();
        this.dateandtime();
    }
          
    public void dateandtime() {    
       DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd-MM-yyyy");  
       LocalDateTime now = LocalDateTime.now();
       date.setText(dtf.format(now));
      }   
    public void initialvalues(){
        for(int i=0;i<def_val.length;i++){def_val[i]="0";}
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        prints = new javax.swing.JTextField();
        laminations = new javax.swing.JTextField();
        xerox = new javax.swing.JTextField();
        clrprints = new javax.swing.JTextField();
        photos = new javax.swing.JTextField();
        idcards = new javax.swing.JTextField();
        items = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        others_cre = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        phonepe = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        balance = new javax.swing.JLabel();
        sal = new javax.swing.JTextField();
        hak = new javax.swing.JTextField();
        other_deb = new javax.swing.JTextField();
        rent = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        trans = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        profit = new javax.swing.JLabel();
        tot_bal = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 255));
        jLabel1.setText(" STATEMENT ENTRY FORM");
        jLabel1.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        date.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("SUBMIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel2.setText("Xerox");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 50, 20));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel3.setText("Prints");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 50, 20));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel4.setText("Photos");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 50, 20));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel5.setText("Color Prints");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 90, 20));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel6.setText("Laminations");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 90, 20));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel7.setText("ID Cards");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 70, 20));

        prints.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        prints.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                printsFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                printsFocusLost(evt);
            }
        });
        prints.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                printsMouseClicked(evt);
            }
        });
        prints.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printsActionPerformed(evt);
            }
        });
        prints.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                printsKeyPressed(evt);
            }
        });
        jPanel2.add(prints, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 150, 25));

        laminations.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        laminations.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                laminationsFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                laminationsFocusLost(evt);
            }
        });
        laminations.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                laminationsMouseClicked(evt);
            }
        });
        laminations.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                laminationsKeyPressed(evt);
            }
        });
        jPanel2.add(laminations, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 150, 25));

        xerox.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        xerox.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                xeroxFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                xeroxFocusLost(evt);
            }
        });
        xerox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                xeroxMouseClicked(evt);
            }
        });
        xerox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                xeroxKeyPressed(evt);
            }
        });
        jPanel2.add(xerox, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 150, 25));

        clrprints.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        clrprints.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                clrprintsFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                clrprintsFocusLost(evt);
            }
        });
        clrprints.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clrprintsMouseClicked(evt);
            }
        });
        clrprints.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                clrprintsKeyPressed(evt);
            }
        });
        jPanel2.add(clrprints, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 150, 25));

        photos.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        photos.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                photosFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                photosFocusLost(evt);
            }
        });
        photos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                photosMouseClicked(evt);
            }
        });
        photos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                photosKeyPressed(evt);
            }
        });
        jPanel2.add(photos, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 150, 25));

        idcards.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        idcards.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                idcardsFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                idcardsFocusLost(evt);
            }
        });
        idcards.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                idcardsMouseClicked(evt);
            }
        });
        idcards.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                idcardsKeyPressed(evt);
            }
        });
        jPanel2.add(idcards, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 150, 25));

        items.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        items.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                itemsFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                itemsFocusLost(evt);
            }
        });
        items.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itemsMouseClicked(evt);
            }
        });
        items.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                itemsKeyPressed(evt);
            }
        });
        jPanel2.add(items, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 150, 25));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel10.setText("Gift Items");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 90, 20));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel11.setText("Others");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, 20));

        others_cre.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        others_cre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                others_creFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                others_creFocusLost(evt);
            }
        });
        others_cre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                others_creMouseClicked(evt);
            }
        });
        others_cre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                others_creKeyPressed(evt);
            }
        });
        jPanel2.add(others_cre, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, 150, 25));

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel20.setText("PhonePe");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, -1, 20));

        phonepe.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        phonepe.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                phonepeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                phonepeFocusLost(evt);
            }
        });
        phonepe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                phonepeMouseClicked(evt);
            }
        });
        phonepe.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                phonepeKeyPressed(evt);
            }
        });
        jPanel2.add(phonepe, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, 150, 25));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel9.setText("Salaries");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel12.setText("Hakeem");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel13.setText("Others");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel14.setText("Shop Rent");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        balance.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        balance.setForeground(new java.awt.Color(0, 0, 225));
        jPanel3.add(balance, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 150, 20));

        sal.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        sal.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                salFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                salFocusLost(evt);
            }
        });
        sal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salMouseClicked(evt);
            }
        });
        sal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                salKeyPressed(evt);
            }
        });
        jPanel3.add(sal, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 150, 25));

        hak.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        hak.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                hakFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                hakFocusLost(evt);
            }
        });
        hak.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hakMouseClicked(evt);
            }
        });
        hak.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                hakKeyPressed(evt);
            }
        });
        jPanel3.add(hak, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 150, 25));

        other_deb.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        other_deb.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                other_debFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                other_debFocusLost(evt);
            }
        });
        other_deb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                other_debMouseClicked(evt);
            }
        });
        other_deb.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                other_debKeyPressed(evt);
            }
        });
        jPanel3.add(other_deb, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 150, 25));

        rent.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        rent.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                rentFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                rentFocusLost(evt);
            }
        });
        rent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rentMouseClicked(evt);
            }
        });
        rent.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                rentKeyPressed(evt);
            }
        });
        jPanel3.add(rent, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 150, 25));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel18.setText("Cash On Hand");
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 110, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton2.setText("Calculate");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, 110, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel15.setText("D1 to D2");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, 30));

        trans.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        trans.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                transFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                transFocusLost(evt);
            }
        });
        trans.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                transMouseClicked(evt);
            }
        });
        trans.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                transKeyPressed(evt);
            }
        });
        jPanel3.add(trans, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 150, 25));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setText("CREDITS");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setText("DEBITS");

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel19.setText("Total Balance");

        profit.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        profit.setForeground(new java.awt.Color(0, 0, 225));
        profit.setToolTipText("");

        tot_bal.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        tot_bal.setForeground(new java.awt.Color(0, 0, 225));
        tot_bal.setToolTipText("");

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel21.setText("Profit");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(tot_bal, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel19))
                    .addComponent(profit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(314, 314, 314)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(243, 243, 243)
                        .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel17)
                        .addGap(230, 230, 230))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel19)
                        .addGap(18, 18, 18)
                        .addComponent(tot_bal, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(profit, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 797, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    public String balance_check(){
        Double bal=0.0;
        JTextField[] fields={xerox,prints,photos,clrprints,laminations,idcards,items,others_cre,sal,hak,other_deb,rent,trans};
        for(int i=0;i<fields.length-5;i++){
                if (fields[i].getText() != null && fields[i].getText().isEmpty()){
                    bal+=0;}
                else{
                    bal+=Double.parseDouble(fields[i].getText());
                }
            }
        String pp=phonepe.getText();
        if(pp.equals("")){pp="0";}
        tot_bal.setText(Double.toString(bal+Double.parseDouble(pp)));
        for(int i=fields.length-5;i<fields.length;i++){
                if (fields[i].getText() != null && fields[i].getText().isEmpty()){
                    bal-=0;}
                else{
                    bal-=Double.parseDouble(fields[i].getText());
                }
            }
        return Double.toString(bal);
    }
    public void bal(String amt){
        try {
            conn=Database.connect();
            String ba = null;
            Statement statement = conn.createStatement();
            String sql="SELECT * FROM banks WHERE name ='SBI-SB'";
            ResultSet rs = statement.executeQuery(sql);
            while(rs.next()){
                ba=rs.getString(2);
            }
            ba=Double.toString(Double.parseDouble(ba)+Double.parseDouble(amt));
            sql="UPDATE banks SET balance='"+ba+"' WHERE name ='SBI-SB'";
            PreparedStatement pstmt = conn.prepareStatement(sql);
            pstmt.executeUpdate();
        } catch (SQLException | NumberFormatException ex) {
            JOptionPane.showMessageDialog(null,ex.getMessage());
        }
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String sql = "INSERT INTO accounts VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
        JTextField[] fields={xerox,prints,photos,clrprints,laminations,idcards,items,others_cre,sal,hak,other_deb,rent,phonepe};
        try {
            conn=Database.connect();
            String da=date.getText();
            PreparedStatement pstmt = conn.prepareStatement(sql);
            pstmt.setString(1,da);
            for(int i=0;i<fields.length;i++){
                if (fields[i].getText() != null && fields[i].getText().isEmpty()){
                    pstmt.setString(i+2,null);}
                else{
                    pstmt.setString(i+2,fields[i].getText());
                }
            }
            if(balance.getText().equals("")){
            pstmt.setString(15, "0");}
            else{pstmt.setString(15, balance.getText());}
            if(phonepe.getText().equals("")){
            bal("0");}
            else{bal(phonepe.getText());}
            pstmt.executeUpdate();
            JOptionPane.showMessageDialog(null,"Successfully Stored");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null,e.getMessage());
        }finally{
            try {
                conn.close();
                for(int i=0;i<fields.length;i++){
                    fields[i].setText("");
                }
                trans.setText("");
                phonepe.setText("");
                balance.setText("");
                profit.setText("");
                tot_bal.setText("");
            } catch (SQLException ex) {
                Logger.getLogger(StatementEntry.class.getName()).log(Level.SEVERE, null, ex);
            }
}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String cbal=balance_check();
        balance.setText(cbal);
        String pp=phonepe.getText(),tra=trans.getText();
        if(pp.equals("")){pp="0";}
        if(tra.isEmpty()){tra="0";}
        profit.setText(Double.toString(Double.parseDouble(cbal)+Double.parseDouble(pp)+Double.parseDouble(tra)));
    }//GEN-LAST:event_jButton2ActionPerformed

    public void datachange(int i){
        JTextField[] fields={xerox,prints,photos,clrprints,laminations,idcards,items,others_cre,phonepe,sal,hak,other_deb,rent,trans};
        if(fields[i].getText().isEmpty()){fields[i].setText("0");}
        def_val[i]=Double.toString(Double.parseDouble(def_val[i])+Double.parseDouble(fields[i].getText()));
        fields[i].setText(def_val[i]);
        fields[i].selectAll();
//        jButton1.requestFocusInWindow();
    }
    
    private void xeroxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xeroxMouseClicked
        // TODO add your handling code here:
         xerox.setText("");
    }//GEN-LAST:event_xeroxMouseClicked

    private void xeroxFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_xeroxFocusGained
        // TODO add your handling code here:
        xerox.setText("");
    }//GEN-LAST:event_xeroxFocusGained

    private void xeroxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_xeroxKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            datachange(0);
        }
    }//GEN-LAST:event_xeroxKeyPressed

    private void xeroxFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_xeroxFocusLost
        // TODO add your handling code here:
        xerox.setText(def_val[0]);
    }//GEN-LAST:event_xeroxFocusLost

    private void printsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_printsActionPerformed

    private void printsFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_printsFocusGained
        // TODO add your handling code here:
        prints.setText("");
    }//GEN-LAST:event_printsFocusGained

    private void printsFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_printsFocusLost
        // TODO add your handling code here:
        prints.setText(def_val[1]);
    }//GEN-LAST:event_printsFocusLost

    private void printsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_printsKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            datachange(1);
        }
    }//GEN-LAST:event_printsKeyPressed

    private void printsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_printsMouseClicked
        prints.setText("");
    }//GEN-LAST:event_printsMouseClicked

    private void photosFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_photosFocusGained
        // TODO add your handling code here:
        photos.setText("");
    }//GEN-LAST:event_photosFocusGained

    private void photosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_photosMouseClicked
        // TODO add your handling code here:
        photos.setText("");
    }//GEN-LAST:event_photosMouseClicked

    private void photosFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_photosFocusLost
        // TODO add your handling code here:
        photos.setText(def_val[2]);
    }//GEN-LAST:event_photosFocusLost

    private void photosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_photosKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            datachange(2);
        }
    }//GEN-LAST:event_photosKeyPressed

    private void clrprintsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_clrprintsKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            datachange(3);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_clrprintsKeyPressed

    private void clrprintsFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_clrprintsFocusGained
        // TODO add your handling code here:
        clrprints.setText("");
    }//GEN-LAST:event_clrprintsFocusGained

    private void clrprintsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clrprintsMouseClicked
        // TODO add your handling code here:
        clrprints.setText("");
    }//GEN-LAST:event_clrprintsMouseClicked

    private void clrprintsFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_clrprintsFocusLost
        // TODO add your handling code here:
        clrprints.setText(def_val[3]);
    }//GEN-LAST:event_clrprintsFocusLost

    private void laminationsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_laminationsKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            datachange(4);
        }    
    }//GEN-LAST:event_laminationsKeyPressed

    private void laminationsFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_laminationsFocusGained
        // TODO add your handling code here:
        laminations.setText("");
    }//GEN-LAST:event_laminationsFocusGained

    private void laminationsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_laminationsMouseClicked
        // TODO add your handling code here:
        laminations.setText("");
    }//GEN-LAST:event_laminationsMouseClicked

    private void laminationsFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_laminationsFocusLost
        // TODO add your handling code here:
        laminations.setText(def_val[4]);
    }//GEN-LAST:event_laminationsFocusLost

    private void idcardsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_idcardsMouseClicked
        // TODO add your handling code here:
        idcards.setText("");
    }//GEN-LAST:event_idcardsMouseClicked

    private void idcardsFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_idcardsFocusGained
        // TODO add your handling code here:
        idcards.setText("");
    }//GEN-LAST:event_idcardsFocusGained

    private void idcardsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idcardsKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            datachange(5);
        }
    }//GEN-LAST:event_idcardsKeyPressed

    private void idcardsFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_idcardsFocusLost
        // TODO add your handling code here:
        idcards.setText(def_val[5]);
    }//GEN-LAST:event_idcardsFocusLost

    private void itemsFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_itemsFocusLost
        // TODO add your handling code here:
        items.setText(def_val[6]);
    }//GEN-LAST:event_itemsFocusLost

    private void itemsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemsMouseClicked
        // TODO add your handling code here:
        items.setText("");
    }//GEN-LAST:event_itemsMouseClicked

    private void itemsFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_itemsFocusGained
        // TODO add your handling code here:
        items.setText("");
    }//GEN-LAST:event_itemsFocusGained

    private void itemsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_itemsKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            datachange(6);
        }
    }//GEN-LAST:event_itemsKeyPressed

    private void others_creKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_others_creKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            datachange(7);
        }
    }//GEN-LAST:event_others_creKeyPressed

    private void others_creFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_others_creFocusGained
        // TODO add your handling code here:
        others_cre.setText("");
    }//GEN-LAST:event_others_creFocusGained

    private void others_creMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_others_creMouseClicked
        // TODO add your handling code here:
        others_cre.setText("");
    }//GEN-LAST:event_others_creMouseClicked

    private void others_creFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_others_creFocusLost
        // TODO add your handling code here:
        others_cre.setText(def_val[7]);
    }//GEN-LAST:event_others_creFocusLost

    private void phonepeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_phonepeFocusLost
        // TODO add your handling code here:
        phonepe.setText(def_val[8]);
    }//GEN-LAST:event_phonepeFocusLost

    private void phonepeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_phonepeFocusGained
        // TODO add your handling code here:
        phonepe.setText("");
    }//GEN-LAST:event_phonepeFocusGained

    private void phonepeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_phonepeMouseClicked
        // TODO add your handling code here:
        phonepe.setText("");
    }//GEN-LAST:event_phonepeMouseClicked

    private void phonepeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phonepeKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            datachange(8);
        }
    }//GEN-LAST:event_phonepeKeyPressed

    private void salKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_salKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            datachange(9);
        }
    }//GEN-LAST:event_salKeyPressed

    private void hakKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_hakKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            datachange(10);
        }
    }//GEN-LAST:event_hakKeyPressed

    private void other_debKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_other_debKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            datachange(11);
        }
    }//GEN-LAST:event_other_debKeyPressed

    private void rentKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rentKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            datachange(12);
        }
    }//GEN-LAST:event_rentKeyPressed

    private void transKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_transKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            datachange(13);
        }
    }//GEN-LAST:event_transKeyPressed

    private void salMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salMouseClicked
        // TODO add your handling code here:
        sal.setText("");
    }//GEN-LAST:event_salMouseClicked

    private void salFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_salFocusGained
        // TODO add your handling code here:
        sal.setText("");
    }//GEN-LAST:event_salFocusGained

    private void salFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_salFocusLost
        // TODO add your handling code here:
        sal.setText(def_val[9]);
    }//GEN-LAST:event_salFocusLost

    private void hakFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_hakFocusGained
        // TODO add your handling code here:
        hak.setText("");
    }//GEN-LAST:event_hakFocusGained

    private void hakMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hakMouseClicked
        // TODO add your handling code here:
        hak.setText("");
    }//GEN-LAST:event_hakMouseClicked

    private void hakFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_hakFocusLost
        // TODO add your handling code here:
        hak.setText(def_val[10]);
    }//GEN-LAST:event_hakFocusLost

    private void other_debFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_other_debFocusLost
        // TODO add your handling code here:
        other_deb.setText(def_val[11]);
    }//GEN-LAST:event_other_debFocusLost

    private void other_debFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_other_debFocusGained
        // TODO add your handling code here:
        other_deb.setText("");
    }//GEN-LAST:event_other_debFocusGained

    private void other_debMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_other_debMouseClicked
        // TODO add your handling code here:
        other_deb.setText("");
    }//GEN-LAST:event_other_debMouseClicked

    private void rentFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_rentFocusGained
        // TODO add your handling code here:
        rent.setText("");
    }//GEN-LAST:event_rentFocusGained

    private void rentFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_rentFocusLost
        // TODO add your handling code here:
        rent.setText(def_val[12]);
    }//GEN-LAST:event_rentFocusLost

    private void rentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rentMouseClicked
        // TODO add your handling code here:
        rent.setText("");
    }//GEN-LAST:event_rentMouseClicked

    private void transFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_transFocusGained
        // TODO add your handling code here:
        trans.setText("");
    }//GEN-LAST:event_transFocusGained

    private void transFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_transFocusLost
        // TODO add your handling code here:
        trans.setText(def_val[13]);
    }//GEN-LAST:event_transFocusLost

    private void transMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transMouseClicked
        // TODO add your handling code here:
        trans.setText("");
    }//GEN-LAST:event_transMouseClicked

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StatementEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StatementEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StatementEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StatementEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StatementEntry().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel balance;
    private javax.swing.JTextField clrprints;
    private javax.swing.JLabel date;
    private javax.swing.JTextField hak;
    private javax.swing.JTextField idcards;
    private javax.swing.JTextField items;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField laminations;
    private javax.swing.JTextField other_deb;
    private javax.swing.JTextField others_cre;
    private javax.swing.JTextField phonepe;
    private javax.swing.JTextField photos;
    private javax.swing.JTextField prints;
    private javax.swing.JLabel profit;
    private javax.swing.JTextField rent;
    private javax.swing.JTextField sal;
    private javax.swing.JLabel tot_bal;
    private javax.swing.JTextField trans;
    private javax.swing.JTextField xerox;
    // End of variables declaration//GEN-END:variables
}
